

# Import all barcode_data_processed files generated by ProcessXcaliburoutput.R that want to merge
# Merge them, make data.frame and replace nas with zero.
H<-barcode_data_processed1.9A
U<-barcode_data_processed10.96A
M<-barcode_data_processed11A
E<-barcode_data_processed2A
N<-merge(H, U, by.x="name", all=TRUE)
O<-merge(N, M, by.x="name", all=TRUE)
D<-merge(O, E, by.x="name", all=TRUE)
D<-as.data.frame(D)
D[is.na(D)] <- 0

# Import the txt file with names and link to plate and sample index
d<- Names.AE13A

# Rename read count table/ adapt accordingly
# The sequencing run identiffier is removed
# The plate index sequences are given their number
names(D) <- gsub("A1166R0", "", names(D))
names(D) <- gsub("A1166R", "", names(D))
names(D) <- gsub("TGTGACGT", "1", names(D))
names(D) <- gsub("AACAACCG", "2", names(D))
names(D) <- gsub("ACGGAATG", "8", names(D))
names(D) <- gsub("CTAACTCC", "18", names(D))
names(D) <- gsub("GATGGTCA", "19", names(D))
names(D) <- gsub("TGGCAGAA", "23", names(D))

# Remove nohit columns
D = D[,!grepl("_nohit_cols$",names(D))]

# Reformulate indentifier table
d$index <- paste(d$Sample.index, d$Plate.index, sep='_') 
d$Name <- paste(d$name, d$Plate.index, sep='_') 
d$Name <- paste(d$Name, d$Sample.index, sep='_')
d$Sample.index <- NULL
d$Plate.index <- NULL
d$name <- NULL
d<-t(d)
rownames(d)<-NULL
colnames(d)= d[1,]
d = d[-1,]
d<-t(d)

# Merge the two
L<-merge(D, d, all=TRUE)

# Export table to look at hits/nohits and readcounts in excel
# name ending here is "1_withnames"
write.table(L,"/Users/Almut/Desktop/AE13A 1_withnames.txt",row.names=TRUE,col.names=NA, sep="\t")



